### ISSUE TITLE
Failed to mount component

### ISSUE THREAD

**Issue by ShuminKong** [alvarotrigo/vue-fullpage.js#5]
When I tried out the basic usage I get this error. All dependencies installed. Any hints?

```
vue.esm.js?efeb:578 [Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <FullPage>
       <App> at src/App.vue
         <Root>
warn @ vue.esm.js?efeb:578
23:05:49.499 
```

Thanks in advance.

**Comment by alvarotrigo** [comment]
Have you tried running the examples to see if it all works well for you?

First install the node dependencies:

```
npm install
```

Then use:

```
npm run-script demo1
```

**Comment by ShuminKong** [comment]
Yes I cloned the repo and did that.. It was all good on the demo.

**Comment by ShuminKong** [comment]
After I move the entire source code of the package into the module. This is resolved.

Before I installed this package with npm.. Maybe it's time to update it?

**Comment by alvarotrigo** [comment]
> Yes I cloned the repo and did that.. It was all good on the demo.

Perhaps you missed the [.babelrc file](https://github.com/alvarotrigo/vue-fullpage.js/blob/master/.babelrc)? Which is hidden?

I was able to run the demo after installing it with npm, so I do not think there's an issue there. 
I'll close the issue for now.

**Comment by ShuminKong** [comment]
After carefully inspect my vue-fullpage directory created by npm. There's no filed ends with .vue. Is it normal? I think it could be something wrong with my npm..

**Comment by alvarotrigo** [comment]
what about `src/FullPage.vue`?

**Comment by ShuminKong** [comment]
There's no `vue-fullpage/src` directory. Something must be seriously wrong with my npm. I'll just move the source code there. Thanks for help!

**Comment by alvarotrigo** [comment]
You might be installing the wrong component :)
`vue-fullpage.js`, not `vue-fullpage` :)

```
npm install vue-fullpage.js
```

**Comment by ShuminKong** [comment]
You got it!! I thought it's weird to have `.js` in the package name and I was wrong....

**Comment by alvarotrigo** [comment]
:) 
Yeah... someone took that module name before me!
